
version: "3"
services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: dockerdb
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: djemals123
#      MYSQL_USER: root
#      MYSQL_PASSWORD : djemals123
      TZ: 'Asia/Seoul'
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
#    networks:
#      - docker_network
    ports:
      - 3307:3306
#    volumes:
#      - ./mysql/conf.d:/etc/mysql/conf.d # MySQL 설정 파일
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10


  redis:
    container_name: redis_container
    image: redis:7.0.8
    ports:
      - 6379:6379
#    networks:
#      - docker_network


  application:
    container_name: springboot_container
    build: .
    ports:
      - 5000:8080
    depends_on:
      - mysql
      - redis
    restart: always
#    networks:
#      - docker_network


#networks:
#  docker_network:


